# Generated by Django 5.1.7 on 2026-05-26 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_add_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_action__74f5dd_idx',
            old_name='audit_aud_action__3d756c_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_emissio_1d9d6a_idx',
            old_name='audit_aud_emissio_9cd0c2_idx',
        ),
    ]
