SOURCE_TYPE_SAP = "sap"
SOURCE_TYPE_UTILITY = "utility"
SOURCE_TYPE_TRAVEL = "travel"

SOURCE_TYPES = [
    (SOURCE_TYPE_SAP, "SAP"),
    (SOURCE_TYPE_UTILITY, "Utility"),
    (SOURCE_TYPE_TRAVEL, "Travel"),
]

INGESTION_STATUS_PENDING = "pending"
INGESTION_STATUS_PROCESSING = "processing"
INGESTION_STATUS_COMPLETED = "completed"
INGESTION_STATUS_FAILED = "failed"

INGESTION_STATUSES = [
    (INGESTION_STATUS_PENDING, "Pending"),
    (INGESTION_STATUS_PROCESSING, "Processing"),
    (INGESTION_STATUS_COMPLETED, "Completed"),
    (INGESTION_STATUS_FAILED, "Failed"),
]

VALIDATION_STATUS_VALID = "valid"
VALIDATION_STATUS_FLAGGED = "flagged"
VALIDATION_STATUS_REJECTED = "rejected"

VALIDATION_STATUSES = [
    (VALIDATION_STATUS_VALID, "Valid"),
    (VALIDATION_STATUS_FLAGGED, "Flagged"),
    (VALIDATION_STATUS_REJECTED, "Rejected"),
]

ANALYST_STATUS_PENDING = "pending"
ANALYST_STATUS_APPROVED = "approved"
ANALYST_STATUS_REJECTED = "rejected"
ANALYST_STATUS_LOCKED = "locked"

ANALYST_STATUSES = [
    (ANALYST_STATUS_PENDING, "Pending"),
    (ANALYST_STATUS_APPROVED, "Approved"),
    (ANALYST_STATUS_REJECTED, "Rejected"),
    (ANALYST_STATUS_LOCKED, "Locked"),
]

ACTION_APPROVE = "approve"
ACTION_REJECT = "reject"
ACTION_NOTE = "note"
ACTION_LOCK = "lock"
ACTION_STATUS_CHANGE = "status_change"

AUDIT_ACTION_INGESTED = "ingested"
AUDIT_ACTION_PARTIAL_UPDATE = "partial_update"
