# Generated by Django 5.1.7 on 2026-05-26 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_add_operational_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='datasource',
            new_name='ingestion_d_organiz_c6b96d_idx',
            old_name='ingestion_d_organiz_403631_idx',
        ),
        migrations.RenameIndex(
            model_name='datasource',
            new_name='ingestion_d_ingesti_da1728_idx',
            old_name='ingestion_d_ingesti_a29748_idx',
        ),
        migrations.RenameIndex(
            model_name='rawrecord',
            new_name='ingestion_r_data_so_695d29_idx',
            old_name='ingestion_r_data_so_dfd14d_idx',
        ),
    ]
