# Generated by Django 5.1.7 on 2026-05-26 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_add_name_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='organization',
            new_name='organizatio_name_537540_idx',
            old_name='organizatio_name_7b06eb_idx',
        ),
    ]
